DELIMITER //
CREATE PROCEDURE P_CHK_ACTIVITY
(OUT O_RESULT INT(1))
BEGIN
	DECLARE C_ACTIVITY CURSOR FOR SELECT ID FROM ACTIVITIES WHERE STATUS = 1 AND START_TIME < now() AND END_TIME < now();
	DECLARE EXIT HANDLER FOR SQLWARNING,NOT FOUND,SQLEXCEPTION SET O_RESULT = -1;
    
	OPEN 
    
END;